package com.Anbu.TaskManagementSystem.model.employee;

public enum Permission {

    EMPLOYEE_CREATE,
    EMPLOYEE_UPDATE,
    EMPLOYEE_VIEW,
    PROJECT_CREATE,
    PROJECT_UPDATE,
    PROJECT_VIEW,
    TICKET_CREATE,
    TICKET_UPDATE,
    TICKET_VIEW,
    TICKET_DELETE,
    PROJECT_MEMBERS_MANAGE,
    OWN_PROFILE;

    /*ADMIN_CREATE,
    ADMIN_READ,
    ADMIN_UPDATE,
    ADMIN_DELETE,
    MANAGER_CREATE,
    MANAGER_READ,
    MANAGER_UPDATE,
    MANAGER_DELETE,
    USER_CREATE,
    USER_READ,
    USER_UPDATE,
    USER_DELETE,
    PROFILE_UPDATE;*/
}
